E:\Academics\DDP\Code\CNN\droplet-parameter-estimation\infocus\all
['data', 'dataset', 'main.py', 'model', 'resume.py', 'test.py', 'wandb']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    img, label = next(iter(train_dataloader))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Academics\DDP\Code\CNN\droplet-parameter-estimation\infocus\all\dataset\droplets.py", line 46, in __getitem__
    label = [float(self.csv.iloc[idx, 1]), float(self.csv.iloc[idx, 2])]
  File "C:\Users\unnik\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\unnik\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "C:\Users\unnik\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "C:\Users\unnik\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "C:\Users\unnik\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds